api_platform:
    title: 'Symfony REST API Platform'
    description: 'A REST API with API Platform to manage a simple app.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
